version: '3.9'
services:
  db:
    image: postgres
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: nest-playground
      POSTGRES_USER: nest-playground
      POSTGRES_PASSWORD: nest-playground
